# Generated by Django 4.1.7 on 2023-03-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referal',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
