# Generated by Django 4.1.7 on 2023-03-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuser_referal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='people_invited_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
